name: Build and deploy ASP.Net Core app to Azure Web App - desafio-pessoas

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Set up Node.js for Vite
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./pessoas.client

      - name: Build frontend
        run: npm run build
        working-directory: ./pessoas.client

      - name: Build .NET app
        run: dotnet build --configuration Release

      - name: Publish .NET app
        run: dotnet publish -c Release -o ./publish

      - name: List published files (debug)
        run: dir ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5FF75F1A31E44736B1AB2A9282EF1901 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B2B79059C501460D9637CA5F75FB378A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6B3E471DEAD4C5882DE1A02E83201EB }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'desafio-pessoas'
          slot-name: 'Production'
          package: ./publish
