name: Build and deploy ASP.Net Core app to Azure Web App - desafio-pessoas

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Set up Node.js for Vite
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ajuste para a versão que seu projeto utiliza

      - name: Install dependencies (npm)
        run: npm install
        working-directory: ./pessoas.client  # Caminho para a pasta do seu frontend

      - name: Build frontend (Vite)
        run: npm run build
        working-directory: ./pessoas.client  # Caminho para a pasta do seu frontend

      - name: Build .NET app
        run: dotnet build --configuration Release

      - name: Publish .NET app
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      # Passo para listar os arquivos no diretório de publicação
      - name: List files in the publish directory
        run: |
          echo "Listing files in the publish directory:"
          dir "${{env.DOTNET_ROOT}}\\myapp"  # Usando a barra invertida para caminhos no Windows

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5FF75F1A31E44736B1AB2A9282EF1901 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B2B79059C501460D9637CA5F75FB378A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6B3E471DEAD4C5882DE1A02E83201EB }}

      # Passo para verificar o conteúdo da pasta de artefato antes do deploy
      - name: Check files in the publish directory
        run: |
          echo "Listing files in ${{env.DOTNET_ROOT}}\\myapp"
          dir "${{env.DOTNET_ROOT}}\\myapp"  # Usando a barra invertida para caminhos no Windows

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'desafio-pessoas'
          slot-name: 'Production'
          package: "${{env.DOTNET_ROOT}}/myapp/"  # Caminho completo, com barra final
